### ISSUE TITLE
Gestion des produits groupés

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-1click-magento#102]
https://one-click-api.readme.io/reference
@mehdichaouch est ce qu'on peut utiliser le bouton panier pour gérer ca?

**Comment by mehdichaouch** [comment]
Implémentation dans la lib de AuthorizeV2 et utilisation de cette méthode seulement pour les produits groupés. Fonctionnera seulement avec les produits groupés contenant que des produits simples.

**Comment by StefBrito** [comment]
![image](https://user-images.githubusercontent.com/33653542/34664997-f10209c6-f45e-11e7-94f2-660015780bf2.png)
Lorsqu'un produit groupé est créé, nous ne pouvons pas établir de quantité minimale au lot 

![image](https://user-images.githubusercontent.com/33653542/34665109-53f22c1e-f45f-11e7-8978-62ed48955370.png)

Le bouton ne s'affiche donc pas car il ne relève aucunes quantités. Le Block Oyst_OneClick_Block_OneClick est bien dans le template demandé.

![image](https://user-images.githubusercontent.com/33653542/34665512-b627d590-f460-11e7-80e5-6b325889558e.png)
Le module doit donc récupérer les quantités des super_group_id, ainsi que l'id correspond au produit indiqué dans le super group.

Le stock est automatiquement géré par produits simples dans magento ce qui ne devrait pas être gênant pour le module avec la gestion des stocks déjà associée.

**Comment by StefBrito** [comment]
Release

**Comment by StefBrito** [comment]
release
