### ISSUE TITLE
Prix flat rate x2 lors de la création de commande côté boutique

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-1click-magento#104]
ETQM je configure flat rate à 3 euros: 
![image](https://user-images.githubusercontent.com/27730079/31378597-214240f0-adac-11e7-91a1-821ab6744f54.png)

Je synchronise ce mode de livraison avec le 1-click. 

Sur la pop-in le montant est bien de 3 euros. 

Quand la commande se créé, le montant est de 6 euros et non de 3 euros.

![image](https://user-images.githubusercontent.com/27730079/31378652-4ba48650-adac-11e7-9569-5f0aaee000ec.png)

**Comment by mehdichaouch** [comment]
![image.png](https://images.zenhubusercontent.com/56bc540a6caf56c9d38c6aa5/ecd24387-ec3d-45ed-962b-d6faaa0d2338)
Le problème vient du flate rate par item ou par commande.
Je vois comment faire les calculs en fonction de...
