### ISSUE TITLE
Put 10ru.pt tracker on all pages of a merchant website

### ISSUE THREAD

**Issue by jonasmaumene** [oystparis/oyst-1click-magento#111]
On a merchant back-office, put a parameter that will activate a tracker which would show the following datas : 

```
<script src="https://trk.10ru.pt"></script>

<meta name="oyst_tracker_info_freepay_activated" content="1">
<meta name="oyst_tracker_info_freepay_apikey" content="1">
<meta name="oyst_tracker_environnement_freepay" content="custom">
<meta name="oyst_tracker_info_oneclick_activated" content="1">
<meta name="oyst_tracker_info_oneclick_apikey" content="1">
<meta name="oyst_tracker_environnement_1click" content="custom">
```
wording and display : 
![image](https://user-images.githubusercontent.com/32451092/34936306-2b5b9cb8-f9e1-11e7-8cd8-6a0b57ac43e6.png)

**Comment by rbenezra** [comment]
- [ ] Wording : rajouter le texte en grisé "Activer cette option permet de repérer plus facilement les paiements frauduleux".

**Comment by StefBrito** [comment]
The tracking is working however when you deactivated one-Click the traking is down. It is what we want ?
Maybe it is better to put the traker even if One-click is deactivated. If 1-C is deactivated i can't see if FP is activated.

**Comment by StefBrito** [comment]
Release
