### ISSUE TITLE
Product custom options

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#121]
# As a merchant if I create a custom option costing X euros to the client, 1-click doesn't catch the right price.

I create for example the following custom option : 
![image](https://user-images.githubusercontent.com/32451092/35045379-f347353a-fb93-11e7-8882-74fa5c4ca31d.png)
The client has now the possibility to customize the t-shirt to add a writing on it. This will cost him 20 euros (final = 95 euros = 75 + 20 euros) : 
![image](https://user-images.githubusercontent.com/32451092/35045431-1d425a0e-fb94-11e7-8ec8-3fb8c6f777a0.png)
Yet on the 1-click pop-up the price is still 75 euros : 
![image](https://user-images.githubusercontent.com/32451092/35045514-5b768f52-fb94-11e7-82ec-f3f92630ab16.png)

**Comment by mehdichaouch** [comment]
@rus-daniel for this feature it'll be better to start working on branch ```product-grouped```.
Let me know when you start it to be sure ```product-grouped```is stable and ok to start this issue.
