### ISSUE TITLE
Associated products

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#122]
# Price problem with associated products. 
If a merchant sets a different price for the associated product of a configurable using this menu : 
![image](https://user-images.githubusercontent.com/32451092/35039431-1b3bf28a-fb7e-11e7-9718-894081ef1a89.png)
1-Click doesn't display the modified price : 
![image](https://user-images.githubusercontent.com/32451092/35039466-3b03df74-fb7e-11e7-97a6-0326122c5b82.png)
![image](https://user-images.githubusercontent.com/32451092/35039504-5fadaf6c-fb7e-11e7-88bf-76af1d69cf27.png)

**Comment by StefBrito** [comment]
It is good.

**Comment by StefBrito** [comment]
done
