### ISSUE TITLE
Gestion de la quantité de stock 

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#126]
# ETQP je dois empêcher la commande 1-click hors stock.

Si, ETQC, je modifie la quantité commandée et je dépasse le stock du marchand, lorsque je fais un achat OC un message d'erreur doit apparaître.

Scénarios : 
- Si je mets 0 dans la quantité, 1 seul produit acheté OC : 
![image](https://user-images.githubusercontent.com/32451092/33183670-15ac4246-d079-11e7-82f2-2d0cd37c6002.png)

- Si n est le stock disponible et que je commande m (>n) produits. Message d'erreur avec le stock générique magento.
![image](https://user-images.githubusercontent.com/32451092/33183728-5070c0c8-d079-11e7-866b-a7bf6173f3a5.png)

- Si n est le stock disponible et que je commande m (<=n) produits. m produits apparaissent dans la modale. 

# As a plugin I must deny the client a 1-click order when there is no stock available.

If, as a client, I modify the quantity ordered and I exceed the quantity available in the store, an error message should appear.

Scenarios : 
- If I put 0 in quantity, 1 product should be ordered in the OC modal.
![image](https://user-images.githubusercontent.com/32451092/33183670-15ac4246-d079-11e7-82f2-2d0cd37c6002.png)

-Let n be the quantity available for a product, if i order m (>n) products : pop magento error message.
![image](https://user-images.githubusercontent.com/32451092/33183728-5070c0c8-d079-11e7-866b-a7bf6173f3a5.png)

- Let n be the quantity available for a product, if i order m (<=n) products . m products will appear in the OC modal.

**Comment by mehdichaouch** [comment]
https://one-click-api.readme.io/reference#gestion-du-stock

**Comment by mehdichaouch** [comment]
@rbenezra this new feature have to be enable globally or it have to be configurable via backend?

**Comment by mehdichaouch** [comment]
Stuff to change for QA:
![image.png](https://images.zenhubusercontent.com/56bc540a6caf56c9d38c6aa5/91b9322b-154e-44b1-93b6-10b34cf63c27)
