### ISSUE TITLE
PHP CGI 

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#135]
# Some server config are not compatible with the OC module.

If you go into the ftp of an OVH server, in the "ovh.config" file : 
![image](https://user-images.githubusercontent.com/32451092/34877504-9f8400c2-f7a6-11e7-9416-c8d0aa74a638.png)
 if app.engine is setted as "phpcgi" the oneclick button works. 

If not (setted as "php" or "phpfpm"), the oneclick button doesn't. The modale never appear after a click.

**Comment by mehdichaouch** [comment]
@rbenezra https://en.wikipedia.org/wiki/Common_Gateway_Interface

**Comment by rbenezra** [comment]
TRAVIS
