### ISSUE TITLE
Règle paniers 

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#143]
# ETQP je dois pouvoir gérer les règles paniers magento.

En se basant sur le process des tickets #141 #142 , il faut pouvoir récupérer les règles paniers actives pour un user et pour un certain panier. Celles-ci sont relatives à un groupe client. 

**Tech details :** 

https://one-click-api.readme.io/reference#règles-paniers

**Attention :**
Les règles paniers vont devoir respecter les mêmes règles que spécifiées dans les tickets  #141 #142  

**Test d'acceptance**

https://docs.google.com/document/d/1wneeMgDg4Ce9Kcfidr-shXMBFljDuYgw2cbSUlpvtWQ/edit

**Comment by StefBrito** [comment]
const freeItems = [{
  name: 'Preservatif Illan Five',
  image: 'https://fr.wiktionary.org/wiki/pr%C3%A9servatif#/media/File:Pr%C3%A9servatif_enroul%C3%A9.jpg',
  quantity: 1
}]
const merchantDiscounts = [{
  amount: { currency: 'EUR', value: 1000 },
  description: 'N\'est bien sympa'
}, {
  amount: { currency: 'EUR', value: 3000 },
  description: 'Tiens, cadeau !'
}

Exemple de ce que nous pouvons renvoyer à l'api
