### ISSUE TITLE
Make OC faster

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#155]
# For now, OC on magento is much longer than OC on other CMSs.

- [x] Reduce the data sent to the API for each endpoint may make the process faster (@mehdichaouch)
- [x] Reduce the use of getModel (@rus-daniel)

**Comment by mehdichaouch** [comment]
In sdk:
```composer install --no-dev --optimize-autoloader```

**Comment by StefBrito** [comment]
When the lock is in motion, it is taking too much time.
This action is made for the get.shipments so actually the calling between the api and the plugin is too long.
Clean the code that is useless
