### ISSUE TITLE
[OC]  Refund

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#157]
# For now, when a OC order is completed by a client, it appears on the merchant back office : 
![image](https://user-images.githubusercontent.com/32451092/34111542-4e3d9e62-e40a-11e7-823d-4c1190932aaf.png)

There is a button "Annulation et remboursement" (trad : "Cancel and refund") which triggers the complete refund of the order when clicked by the merchant. 
We need to delete that buton in order to allow the refund by credit memo. All associated actions should be removed (trad ...).
The credit memo should be accessible by the invoice where the online refund should be available. The credit memo of the order should only be offline.

**TECH DETAILS** : 
https://one-click-api.readme.io/reference#remboursement-partiel

example of event to send to oyst API to partially refund an order : 
```
POST /order/v2/orders/ORDER_ID/refunds HTTP/1.1
Host: api.sandbox.oyst.eu
Authorization: Bearer YOUR_API_KEY
Content-Type: application/json
Cache-Control: no-cache

{
	"amount": {
		"value" : 100,
		"currency" : "EUR"
	}
}
```

**Comment by StefBrito** [comment]
Need the changes in the lib to continue this issue

**Comment by StefBrito** [comment]
Release
