### ISSUE TITLE
[FP] Cancel and refund

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#158]
# For now, when a FP transaction is completed 
the order appears on the merchant back-office. Until the capture is triggered on Oyst side, a merchant has the possibility to click on the following actions : 
![image](https://user-images.githubusercontent.com/32451092/34114489-3847f8b0-e413-11e7-8e29-391c125c4bc2.png)

In particular, a merchant can cancel the Freepay order. When the button "Annuler" (trad "cancel") is clicked and confirmer by the merchant, the annulation is made both on merchant back office, and on freepay back-office : 
![image](https://user-images.githubusercontent.com/32451092/34114581-72480ff0-e413-11e7-9b1b-5a2430af8520.png)
![image](https://user-images.githubusercontent.com/32451092/34114884-3fa3b5c6-e414-11e7-8744-18e5bbabb861.png)
![image](https://user-images.githubusercontent.com/32451092/34114909-56481c9a-e414-11e7-8ff4-22da83bc6069.png)

That is the correct behavior of the module. 
Yet, if the capture has been made, a merchant has the possibility to click on the following buttons : 
![image](https://user-images.githubusercontent.com/32451092/34114990-9002527a-e414-11e7-9cc5-e4457fdf787c.png)

The Credit memo can be used to refund an order, but it is not really functionnal. So instead of using this button, we should create a "Freepay Refund" ("Remboursement Freepay" in french) that would allow the merchant to refund partially an order (if a merchant wants to refund totally he would just enter the entire amount of the transaction). 
That button should trigger the reimboursement on Oyst side so that on the Back-office Freepay, the transaction would appear on refunded status.

**TECH DETAILS :** 
https://doc-payments-api.readme.io/reference#remboursement

example of event to send to refund a transaction : 
```
POST /payments/[payment_id]/refund

headers: {Authorization: 'Bearer MerchantApiKey'}

{
 amount: { value: 20000, currency: 'EUR' },
}
```

**Comment by mehdichaouch** [comment]
branch name can be: fp-cancel-refund

**Comment by rbenezra** [comment]
The cancel boutton doesn't work. 
I make a Freepay order, it is not captured yet : 
![image](https://user-images.githubusercontent.com/32451092/34881820-e552e894-f7b4-11e7-8566-381f78a2b6ed.png)

I cancel it from the magento back-office : 
![image](https://user-images.githubusercontent.com/32451092/34881862-036e215e-f7b5-11e7-879a-5bce79ef7270.png)

It is not effective on the Freepay Back-office : 
![image](https://user-images.githubusercontent.com/32451092/34881897-2004695e-f7b5-11e7-8bea-0a13d37fd8c4.png)

This was working before the developpement of the Freepay cancel and refund branch as shown in the ticket above.
