### ISSUE TITLE
Changer la description dans informations produit sur le bouton 1-Click

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-1click-magento#164]
![image](https://user-images.githubusercontent.com/33653542/34663340-a92411b0-f456-11e7-8528-de6a912fc987.png)

Il serait préférable que la description soit :
Activer ou désactiver le bouton 1-Click

**Comment by StefBrito** [comment]
A la place de mettre yes ou no Plutot mettre activé ou désactivé si possible

**Comment by mehdichaouch** [comment]
Est-ce que l'on change le libellé par quelque chose de plus cohérent avec ce qu'on met dans la liste déroulante, à savoir ``Affichage du bouton : Activer / Désactiver```

**Comment by StefBrito** [comment]
Oui cela me parait beaucoup plus cohérent ce serait parfait
