### ISSUE TITLE
Reorganisation backend OneClick

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#167]
# Make the one-click configuration menu clearer for the merchant.

- [ ] A simplified acces to 1-Click configuration via : 
![image](https://user-images.githubusercontent.com/32451092/35162070-60d97112-fd42-11e7-9370-e71bdb9f56f9.png)

- [ ] 6 tabs : French -> "Informations", "1-Click", "Configuration des transporteurs", "Personnalisation du bouton","Gestion des stocks", "Paramètres avancés", "Réinitialisation du module".
English -> "Informations", "1-Click", "Expedition settings", "Custom button", "Stock management","Advanced settings", "Reset module".
![image](https://user-images.githubusercontent.com/32451092/35157471-5a7cdb82-fd34-11e7-806d-4a8676b492f5.png)

- [ ] In "Informations" -> no change.
- [ ] In "1-Click"  -> only keep the following settings : 
- for prod/preprod : 
![image](https://user-images.githubusercontent.com/32451092/35156581-8b639efa-fd31-11e7-80ba-9d293424d6e3.png)
- for sandbox : 
![image](https://user-images.githubusercontent.com/32451092/35156647-c2c1e096-fd31-11e7-8caa-903316edec59.png)
- [ ] In "Configuration des transporteurs" -> 3 under tabs : 
![image](https://user-images.githubusercontent.com/32451092/35161357-412d8d3c-fd40-11e7-998e-95c8c35b8193.png)

wording : French -> "Choix du transporteur par défaut."
"Mapping des méthodes d'expédition certifiées avec 1-Click."
"Mapping des méthodes d'expédition non-certifiées avec 1-Click."
English -> "Default shipping method."
"Shipping methods certified by 1-Click."
"Shipping methods not certified by 1-Click."
- [ ] In  "Choix du transporteur par défaut" -> 
![image](https://user-images.githubusercontent.com/32451092/35161455-99ea857e-fd40-11e7-8e4a-9fd44a260ab0.png)
- [ ] In "Mapping des méthodes d'expédition certifiées avec 1-Click." -> No change
- [ ] In "Mapping des méthodes d'expédition non-certifiées avec 1-Click" -> No change
- [ ] In "Personnalistation du bouton" -> Only keep the following parameters : 
![image](https://user-images.githubusercontent.com/32451092/35161747-6b328f78-fd41-11e7-8d8a-d6af85bc1544.png)
- [ ] In "Gestion des stocks" -> Only keep the following parameters : 
![image](https://user-images.githubusercontent.com/32451092/35161893-de7ae6b0-fd41-11e7-9f65-6c465779fd86.png)
- [ ] In "Paramètres avancés" -> Only keep the following parameters : 
![image](https://user-images.githubusercontent.com/32451092/35162008-30a35b48-fd42-11e7-9a4b-038d3081b0a0.png)
- [ ] In "Réinitialisation du module" : No change.

**Comment by mehdichaouch** [comment]
As I talk, this a to be talk a bit more and/or re-specs.

**Comment by StefBrito** [comment]
release
