### ISSUE TITLE
Clean install desinstall

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#172]
# For now, the installation of the plugin creates tables and settings in the database that are not erased by deleted the module in the magento connect manager.

The non-exhaustive list of the tables and settings are the following : 
- the table "oyst_notification".
- the lines containing "oyst" in the "path" attribute of the table "core_config_data".
- the line “oyst_oneclick_setup”  in the table "resource".

In the configuration menu of One-click, create a tab between "1-Click" and "Configuration des livraisons" : 
![image](https://user-images.githubusercontent.com/32451092/34831018-ff5cf650-f6e5-11e7-8b74-b31dde3d446f.png)

Name it "Réinitialisation du module" : 
![image](https://user-images.githubusercontent.com/32451092/34831139-5f4460a8-f6e6-11e7-9c59-2c1889176317.png)
That buton should trigger the deletion of the tables and settings.

In the configuration of Freepay, in "Paramètres globaux" : 
![image](https://user-images.githubusercontent.com/32451092/34831352-0551e9d4-f6e7-11e7-8e0c-d1df725cfff7.png)

Place the same buton as the above.

**Comment by mehdichaouch** [comment]
Magento Connect n'est pas prévu pour faire cela.
Mais il est possible de faire un bouton dans le BO du module pour supprimer les éléments, tu peux regarder le module de ***Lyra Systempay***

**Comment by rbenezra** [comment]
@mehdichaouch Ok du coup lors d'un désinstall il faudrait d'abord cliquer sur ce bouton puis désinstaller le module ?
Je comprends pas réellement la logique. Lorsqu'un marchand choisit de désinstaller un module, il espère supprimer toutes les composantes de celui-ci. Je trouve un peu tordu et inutilement compliqué de le forcer à passer par un bouton auxiliaire.

**Comment by mehdichaouch** [comment]
@rbenezra oui tout à fait.
Je t'invite à voir ce [How to](http://dhl.support.netresearch.de/support/solutions/articles/12000036213-how-can-i-uninstall-an-extension-) et je reste dispo ou en parler.

**Comment by rbenezra** [comment]
- [ ] Put the "Réinitialisation du module" tab at the end of the OC configuration, after "Mapping des méthodes d'expédition non-certifiées avec 1-Click" .
![image](https://user-images.githubusercontent.com/32451092/34944549-5d4eae4e-fa00-11e7-84d7-4555bd2d9720.png)

- [ ] This button should delete all the settings in database. In particular it should reboot all default parameters. The datas concerning the api key or custom boutton should be deleted.
![image](https://user-images.githubusercontent.com/32451092/34944628-ad95419c-fa00-11e7-872f-0380af9c4a0c.png)
Those datas should be lost after a reset module.
