### ISSUE TITLE
Activation 1-Click button for new products and in each product in catalogue

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#177]
The table where the attribute for 1-Click activation is, is made this way : 
1 if One-Click button appears.
0 if it doesn't.

When a merchant creates new products using an ERP for example, One-Click is not activated for new products. It should. 

One solution would be to activate OC for products where nothing is filled as attribute for activation and for those that have 1.

**Comment by StefBrito** [comment]
To make possible to activate or deactivate the 1C button on a single product :
Example on an other CMS

![image](https://user-images.githubusercontent.com/33653542/34984615-d11627e2-fab1-11e7-9594-1b48e13dc56d.png)

**Comment by rbenezra** [comment]
- [ ] when a merchant creates new products using the magento menu the one-click button should be activated by default.
For now it's not : 
![image](https://user-images.githubusercontent.com/32451092/35053661-0c1180c2-fbab-11e7-8779-e1bac035d19a.png)
![image](https://user-images.githubusercontent.com/32451092/35053693-22f5e44a-fbab-11e7-9fe0-33f7d6c09d97.png)
