### ISSUE TITLE
Ask a confirmation of the reset

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-1click-magento#182]
When i click on the reinitialize button it is uninstalled and reinstalled the module. It should be preferable to ask before the reinitialisation. 

wording : "Êtes-vous sûr de vouloir procéder à la réinitialisation du module ? "
wording: "Do you want to proceed at the reinstallation of the module ?"

You can put a bubble info juste on the side explaining :
" To reinitialize the module execute the flush of all the oyst configurations and notifications in the data base."

french wording : "Réinitialiser le module permet de retirer toutes les configurations et notifications de Oyst dans la Base Données"

**Comment by rbenezra** [comment]
wording : "Êtes-vous sûr de vouloir procéder à la réinitialisation du module ? Cette action est irréversible."

**Comment by mehdichaouch** [comment]
Dans le même cadre de ce ticket on peut ajouter une infobulle à droite du bouton de réinitialisation expliquant ce qui est fait pendant la réinitialisation

Ps : il faut aussi la trad English

**Comment by StefBrito** [comment]
Okay on prend la demande en considération



<http://www.oyst.com/> *Stéphane BRITO*
| *Project Manager Integration*
| t. *+33 1 84 88 89 19*
| e. s <jeremy@oyst.com>tephane.brito@oyst.com

2018-01-23 19:01 GMT+01:00 Mehdi Chaouch <notifications@github.com>:

**Comment by StefBrito** [comment]
Release
