### ISSUE TITLE
Avantages/disadvantages of Quote vs Cart

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-1click-magento#189]
To be more compatible with 3rd party module (coupon, shipping, cart rules, ...) the idea is to see if it's better to use cart than quote in all implementation of module.

Constraint: the cart used by OneClick should have it's own session and be not binded to user session cart. Why? To prevent strange comportment, like when loggin with persistant cart.

To do :
- Explore avantages/disadvantages of Quote vs Cart
  - with 3rd party
  - in perf
  - with maintainability
  - robustest of cart vs quote
- Approx. estimation time of implementation (migration code quote -> cart)

**Comment by Q-Oyst** [comment]
@StefBrito @mehdichaouch l'étude à été faite et la conclusion est qu'on se lance en utilisant le panier sur le bouton page panier ?
Si c'est bien cela le ticket me semble done, qu'en pensez vous ?

**Comment by mehdichaouch** [comment]
Oui tout à fait.

**Comment by StefBrito** [comment]
We are staying on the Quote, more flexibility
