### ISSUE TITLE
Get add_to_cart button data for smart button

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-1click-magento#201]
Smart Button is going to adapte itself to replicate the form of the add_to_cart button.
The parameters available in the BO should be :
- color (already made)
- Width and height (already made)
- Border radius (TO DO)
- Activate/deactivate the smart button (TO DO)

From Magneto backend:
* ```data-smart="true/false"```
* ```data-rounded="true/false"```
* ```data-theme="{default/inverted}"```
* ```data-color="hexa"```

Get add to cart data for: 
* ```data-height="pixel"```
* ```data-width="pixel"```

Activate by default the smart button and border-rounded

**Comment by StefBrito** [comment]
```data-smart='true/false'````
-
```data-rounded='true/false'````
-
```data-theme='{default/inverted}'````
-
```data-color='hexa'````


Directement récupéré nativement par rapport au bouton panier :
```data-height'pixel'````
-
```data-width='pixel'````

**Comment by mehdichaouch** [comment]
@nicolaschenet j'ai ajouté ceci :
![image.png](https://images.zenhubusercontent.com/56bc540a6caf56c9d38c6aa5/ee2df824-19d3-47e3-bb2c-e441ee556b6b)
Mais je n'ai pas le résultat attendu. Est-ce qu'il y a une subtilité ?
Est-ce qu'on peut mettre 1 pour true ; 0 pour false ? comme me le propose nativement Magento et il me semble aussi PrestaShop (cc @feyromain)

**Comment by mehdichaouch** [comment]
@nicolaschenet j'ai eu ma réponse.

**Comment by StefBrito** [comment]
Release
