### ISSUE TITLE
Bug keep the purchase when i got an error

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-1click-magento#248]
Should stop the order when i got an error. Actually when the order is made and we have an error :

- the stock is decremented and not reincrement 
- the purchase is kept and at the end we have made the purchase without seeing the product in the modale

**Comment by mehdichaouch** [comment]
> the purchase is kept and at the end we have made the purchase without seeing the product in the modale
is there an order in magento ?

**Comment by StefBrito** [comment]
release
