### ISSUE TITLE
Rendre indisponible le bouton si champs non renseignés

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-1click-magento#43]
ETQU, je ne dois pas pouvoir cliquer sur le bouton achat en 1-click quand tout les champs des variations sont obligatoires; comme l'ajout au panier qui est impossible si ses champs ne sont pas remplis.

![image](https://user-images.githubusercontent.com/27730079/28621322-d64a9272-7210-11e7-8b54-c06af5635369.png)

**Comment by mehdichaouch** [comment]
Some modifications have been done , but I need some changes on button js.

**Comment by quentinjunior** [comment]
Ok, c'est noté

**Comment by nicolaschenet** [comment]
@mehdichaouch see https://github.com/oystparis/oyst-1click-magento/commit/bef2efe433bcb234863d4cb6016a4cdc718b3e1b##commitcomment-23788158

**Comment by nicolaschenet** [comment]
@mehdichaouch Can you remind me where I can see a demo Magento shop ?

**Comment by mehdichaouch** [comment]
@nicolaschenet you can see demo here www.born3convert.com
