### ISSUE TITLE
ETQM, je n'arrive pas a pousser le json shipments

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-1click-magento#46]
ETQM, je sauvegarde la configuration avec le nouveau json shipments
Puis quand je clique sur envoyer les nouveaux shipments, je recois un message d'erreur

![image](https://user-images.githubusercontent.com/27730079/28710774-9ffc8326-7385-11e7-9835-5e3d5bc4dd84.png)

Dans l'ajax j'ai : Fatal error: Class 'Oyst_OneClick_Exception' not found in /home/bornconvtl/www/app/Mage.php on line 580

**Comment by mehdichaouch** [comment]
![image](https://user-images.githubusercontent.com/861701/28717224-2edfbf70-73a1-11e7-9b6f-bf8cc5e48d93.png)

this is the error!

**Comment by quentinjunior** [comment]
ticket dans le dépot lib.php
