### ISSUE TITLE
Affichage des détails du produits dans la commande dans le BO

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-1click-magento#53]
ETQM, je sais exactement quel produit  a été acheté par le client.

Connaissant l'id unique de la variation du produit  (référence produit, ex : mpd00038) je dois remonter dans le titre de la commande des infos relatives à ce produit (qui sont inscrites en base)

![image](https://user-images.githubusercontent.com/27730079/29016859-78078f1a-7b54-11e7-862f-74c21f2d18ee.png)

Dans un premier temps on travaille sur nos données et sur nos articles. 
Il faut faire un choix sur l'affichage des propriétés qui permettent d'identifier de manière unique la variation du produit. 
Ici on affiche ainsi: titre - type - color - size
![image](https://user-images.githubusercontent.com/27730079/29017042-5f569d66-7b55-11e7-9ae0-fcc977dddbef.png)

**Comment by mehdichaouch** [comment]
this is it 
![image](https://user-images.githubusercontent.com/861701/29465251-f2111cc6-8438-11e7-80df-c46a8a2c4a68.png)
