### ISSUE TITLE
Access logs files

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-1click-magento#65]
Allow to access logs (system.log, Oyst_OneClick.log, exception.log) files from backend.

**Comment by StefBrito** [comment]
To make possible to watch the log in the BO merchant without going in the FTP server.
You can make a file to download in the BO in function of the date that we want.

**Comment by StefBrito** [comment]
@rus-daniel 
There is not the image of Oyst :
![image](https://user-images.githubusercontent.com/33653542/35812859-64b6cb10-0a92-11e8-85c4-2b498b8c22c6.png)

**Comment by StefBrito** [comment]
Release
