### ISSUE TITLE
personnalisation du bouton css

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-1click-magento#67]
Ajouter un champ dans la conf pour customiser l'emplacement du bouton

```
#Oystoneclickcontainer{
position:relative;
top:0;
left:0;
}
```

**Comment by mehdichaouch** [comment]
cf :
https://one-click-api.readme.io/reference#couleur-du-bouton
https://github.com/oystparis/woo-oyst/blob/1click/includes/class-wc-oyst-one-click.php#L453
https://github.com/oystparis/woo-oyst/blob/fb7ff333cb727635aac5568d5bc8d6f5d0b52e96/includes/class-wc-oyst-one-click.php#L1190
