### ISSUE TITLE
image cassées sur page de récap de commande

### ISSUE THREAD

**Issue by jonasmaumene** [oystparis/oyst-1click-magento#72]
![image](https://user-images.githubusercontent.com/25003742/30100726-045d58da-92ea-11e7-9041-d5688b0f1b6c.png)

Image associées au produit :  http://magedemo.dev/media/catalog/product/m/s/msj006c-red_2.jpg (url récupérée en faisant un GET order avec POSTMAN)

**Comment by jonasmaumene** [comment]
testé sur born3convert

**Comment by mehdichaouch** [comment]
Please verify the product via API.
