### ISSUE TITLE
Activation bouton one-click selon le produit 

### ISSUE THREAD

**Issue by rbenezra** [oystparis/oyst-1click-magento#96]
# Actuellement,
 ETQM je peux seulement activer OC sur tous les produits en même temps, ou le désactiver.

ETQM je veux seulement l'activer sur une partie de mon catalogue.

Rajouter un onglet dans les fiches produits :
![sans titre](https://user-images.githubusercontent.com/32451092/31286679-3ee3f1ac-aabf-11e7-832a-4a4c009bf1a5.png)

selon le même modèle que : 
![image](https://user-images.githubusercontent.com/32451092/31286523-b114c892-aabe-11e7-9125-07f78f763a4f.png)
# For now,
As a plugin I can only activate the OC buton on all products, or none.
As a merchant I must be able to activate it only in a part of my catalogue.
Add in a tab in the product page in the catalogue the OC conf : 
![sans titre](https://user-images.githubusercontent.com/32451092/31286679-3ee3f1ac-aabf-11e7-832a-4a4c009bf1a5.png)

Use the following model : 
![image](https://user-images.githubusercontent.com/32451092/31286523-b114c892-aabe-11e7-9125-07f78f763a4f.png)

**Comment by mehdichaouch** [comment]
This is a feature. not a #quickfix not a enhancement.
